#!/usr/bin/env bash
# Script that install Nginx on web-01
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
