#!/usr/bin/env bash
# Script that Configure your Nginx server so that /redirect_me
# is redirecting to another page.

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    
    location /redirect_me {
        rewrite ^ /watch?v=QH2-TGUlwu4 permanent;
    }
}
"

echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
