#!/usr/bin/env bash
# Install nginx and add a custom header
# Configures a brand new ubuntu
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
hostname=$(hostname)
sed_expression="location \/ { add_header X-Served-By $hostname; }"
sed -i "/listen 80 default_server/a $sed_expression" /etc/nginx/sites-available/default
service nginx restart
