#!/usr/bin/env bash
# Install nginx and add a custom header
# Configures a brand new ubuntu
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
service nginx restart
