#!/usr/bin/env bash
# Install nginx and add a custom header
# Configures a brand new ubuntu
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo service nginx restart
