#!/usr/bin/env bash
# Install and configure haproxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 284320-web-01 100.26.10.85 check
   server 284320-web-02 54.158.211.209 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
